# Generated by Django 3.0.5 on 2020-05-14 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlackJack_app', '0002_participants_stand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participants',
            name='stand',
            field=models.BooleanField(default=False),
        ),
    ]
